replicaCount: 1

image:
  repository: mrasap/flask
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP #LoadBalancer
  port: 80 # 8080
  targetPort: 8080 # http

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: aa
  paths:
    - /
  hosts: 
    - abc.com
  tls: 
    - secretName: abc
      hosts:
        - abc

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
